name: Tire Deals Bot

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache DB
        uses: actions/cache@v4
        with:
          path: tirebot.sqlite
          key: tirebot-db
          restore-keys: |
            tirebot-db

      - name: Run
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ALERT_RSS_13: ${{ secrets.ALERT_RSS_13 }}
          ALERT_RSS_14: ${{ secrets.ALERT_RSS_14 }}
          ALERT_RSS_15: ${{ secrets.ALERT_RSS_15 }}
        run: |
          python -m src.main

